"""Typed surface projection IR: Web pack + host projections compiled from canonical sources.

FW-05 / R-AUD-003: the Web pack is the five PIPD semantic documents
(PIPD_BOOTSTRAP.md, PIPD_CANONICAL_CORE.md, PIPD_ROUTER_PROFILES.md,
PIPD_ARTIFACT_SCHEMAS.md, PIPD_EVAL_HANDOFF.md). The site UI five files are
OPTIONAL_SITE_UI and are EXPLICITLY excluded from the Web denominator.

FW-06 / R-AUD-004: the three host projections each carry a field-level
contract, source references, compatibility + capability-loss and an
effective-load result computed by a real typed loader. A marker-only stub
cannot satisfy effective load. Mutations (provider-off, unsupported host,
marker-only stub, permission widening, missing required mapping) FAIL with
typed reasons.

R-AUD-015: everything is compiled from a typed projection IR built out of the
canonical PIPD objects (schemas/registry.json + schemas/*.schema.json), the
profile trio (src/pipd_ls_sp/profiles.py) and the adapter mapping below.
Every emitted artifact is traceable to object id / schema / version / source
hash. A stale source is regenerated by `project_surfaces`; the strict gates
refuse stale artifacts instead of silently accepting them.

S5/S6 are NOT authorised: host checks use fixture/mock contracts and must
never be reported as live HGK/GENIE integration PASS.

This module is additive. It does not touch the requirement compiler, the
pipeline entry points or workspace.project_surfaces; the gates and tests call
`project_surfaces` here.
"""
from __future__ import annotations

import ast
import json
import re
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from .util import canonical_json, sha256_file, sha256_text

SCHEMA_IR = "PIPD-PROJECTION-IR/1"
SCHEMA_DOC_META = "PIPD-WEB-DOC/1"
SCHEMA_HOST_RECORD = "PIPD-HOST-PROJECTION/1"
SCHEMA_HOST_RECEIVER_MAP = "PIPD-HOST-RECEIVER-MAP/1"
SCHEMA_GENIE_CROSSWALK = "PIPD-GENIE-OBJECT-CROSSWALK/1"
SCHEMA_VERSION = "1"

WEB_DOC_KIND = "WEB_DOC"
HOST_KIND = "HOST_PROJECTION"
UI_KIND = "OPTIONAL_SITE_UI"

UI_FILES = ("index.html", "app.js", "styles.css", "manifest.webmanifest", "README.md")
UI_DIR = "OPTIONAL_SITE_UI"
IR_FILE = "PROJECTION_IR.json"

TYPE_VOCAB = {"string", "integer", "number", "boolean", "object", "array", "enum"}

# ---------------------------------------------------------------- typed errors

class ProjectionError(Exception):
    code = "PROJECTION_ERROR"
    mutation = "MUT-UNKNOWN"

    def __init__(self, reason: str = ""):
        super().__init__(reason or self.code)
        self.reason = reason or self.code

    def failure(self, path: str = "") -> dict:
        return {"code": self.code, "mutation": self.mutation,
                "reason": self.reason, "path": path}


class MissingField(ProjectionError):
    code = "MISSING_FIELD"
    mutation = "MUT-MISSING-FIELD"


class EmptyPayload(ProjectionError):
    code = "EMPTY_PAYLOAD"
    mutation = "MUT-EMPTY-PAYLOAD"


class ScopeWidening(ProjectionError):
    code = "SCOPE_WIDENING"
    mutation = "MUT-SCOPE-WIDENING"


class PermissionWidening(ProjectionError):
    code = "PERMISSION_WIDENING"
    mutation = "MUT-HOST-PERMISSION-WIDENING"


class StaleSource(ProjectionError):
    code = "STALE_SOURCE"
    mutation = "MUT-STALE-SOURCE"


class MarkerOnlyStub(ProjectionError):
    code = "MARKER_ONLY_STUB"
    mutation = "MUT-HOST-STUB"


class UnsupportedHost(ProjectionError):
    code = "UNSUPPORTED_HOST"
    mutation = "MUT-HOST-UNSUPPORTED"


class UnsupportedSurface(ProjectionError):
    code = "UNSUPPORTED_SURFACE"
    mutation = "MUT-HOST-UNSUPPORTED"


class ProviderOff(ProjectionError):
    code = "PROVIDER_OFF"
    mutation = "MUT-HOST-PROVIDER-OFF"


class MissingRequiredMapping(ProjectionError):
    code = "MISSING_REQUIRED_MAPPING"
    mutation = "MUT-HOST-MISSING-MAPPING"


class WrongWebSet(ProjectionError):
    code = "WRONG_WEB_SET"
    mutation = "MUT-WEB-WRONGSET"


class DenominatorLeak(ProjectionError):
    code = "DENOMINATOR_LEAK"
    mutation = "MUT-WEB-WRONGSET"


class NotDerived(ProjectionError):
    code = "NOT_DERIVED"
    mutation = "MUT-WEB-WRONGSET"


class MissingRequiredHost(ProjectionError):
    code = "MISSING_REQUIRED_HOST"
    mutation = "MUT-HOST-MISSING"


class HostEntryMissing(ProjectionError):
    code = "HOST_ENTRY_MISSING"
    mutation = "MUT-HOST-MISSING"


class InvalidEntry(ProjectionError):
    code = "INVALID_ENTRY"
    mutation = "MUT-HOST-STUB"


class ParityMismatch(ProjectionError):
    code = "PARITY_MISMATCH"
    mutation = "MUT-PARITY"


class UnknownSourceObject(ProjectionError):
    code = "UNKNOWN_SOURCE_OBJECT"
    mutation = "MUT-HOST-UNKNOWN-SOURCE"


# ---------------------------------------------------------------- adapter mapping

# The canonical adapter mapping (R-AUD-015): host surface -> how canonical
# objects project onto it. It is itself a hashed source object, so every
# artifact derived from it is traceable.
ADAPTER_MAPPING: dict[str, Any] = {
    "schema": "PIPD-ADAPTER-MAPPING/1",
    "version": "1",
    "writable_scope": ["dist/web/**"],
    "routing": {
        "LITE": ["host:generic-skills"],
        "STANDARD": ["host:generic-skills", "host:hgk-receiver", "host:genie-adapter"],
        "ASSURED": ["host:generic-skills", "host:hgk-receiver", "host:genie-adapter"],
    },
    "hosts": {
        "host:generic-skills": {
            "dir": "host_generic-skills",
            "entry_file": "SKILL.md",
            "entry_kind": "skill_projection",
            "loader": "skill_projection_v1",
            "skill_id": "pipd-surface-projection",
            "source_objects": ["S0:SurfaceProjectionManifest", "S0:ProfileBinding",
                               "PROFILE:TRIO", "ADAPTER:MAPPING"],
            "field_contract_sources": ["S0:SurfaceProjectionManifest", "S0:ProfileBinding"],
            "required_mappings": ["S0:SurfaceProjectionManifest", "S0:ProfileBinding"],
            "allowed_permissions": ["read:canonical-objects", "emit:projection"],
            "provider": {"provider_id": "generic-skill-host", "admission_state": "FIXTURE_MOCK",
                         "live_integration": False,
                         "basis": "adapter checks use fixture/mock contracts only"},
            "compatibility_source": None,
            "capability_loss": [
                {"record_type": "CapabilityLoss", "loss_id": "LOSS-GS-01",
                 "capability": "skill execution authority",
                 "reason": "projection carries the skill contract only; execution stays with the host",
                 "severity": "DECLARED"}],
            "nack": [
                {"record_type": "NACK", "nack_id": "NACK-GS-01",
                 "statement": "effective load is a fixture/mock contract load, not a live generic host run",
                 "basis": "S5/S6 NOT_AUTHORISED"},
                {"record_type": "NACK", "nack_id": "NACK-GS-02",
                 "statement": "no live HGK/GENIE integration PASS is claimed by this projection",
                 "basis": "S5/S6 NOT_AUTHORISED"}],
        },
        "host:hgk-receiver": {
            "dir": "host_hgk-receiver",
            "entry_file": "receiver-map.json",
            "entry_kind": "receiver_map",
            "loader": "receiver_map_v1",
            "source_objects": ["S0:ExecutionHandoff", "S0:ExecutionBindingRef",
                               "S0:WorkOrderCandidate", "SEAM:S5", "ADAPTER:MAPPING"],
            "field_contract_sources": ["S0:ExecutionHandoff", "S0:ExecutionBindingRef",
                                       "S0:WorkOrderCandidate"],
            "required_mappings": ["S0:ExecutionHandoff", "S0:ExecutionBindingRef",
                                  "S0:WorkOrderCandidate"],
            "allowed_permissions": ["read:canonical-objects", "emit:projection",
                                    "emit:receiver-map"],
            "provider": {"provider_id": "hgk-execution-receiver", "admission_state": "OFF",
                         "live_integration": False,
                         "basis": "S5 HGK execution receiver canary NOT_AUTHORISED"},
            "compatibility_source": "SEAM:S5",
            "capability_loss": [
                {"record_type": "CapabilityLoss", "loss_id": "LOSS-HR-01",
                 "capability": "runtime authority",
                 "reason": "the typed receiver map is contract-only; the receiver is never executed here",
                 "severity": "DECLARED"},
                {"record_type": "CapabilityLoss", "loss_id": "LOSS-HR-02",
                 "capability": "live receiver ack",
                 "reason": "S5 receiver canary NOT_AUTHORISED; ack/nack state stays contract-level",
                 "severity": "DECLARED"}],
            "nack": [
                {"record_type": "NACK", "nack_id": "NACK-HR-01",
                 "statement": "receiver-map effective load is a fixture/mock contract load, not a live HGK run",
                 "basis": "S5 NOT_AUTHORISED"},
                {"record_type": "NACK", "nack_id": "NACK-HR-02",
                 "statement": "no live HGK integration PASS is claimed by this projection",
                 "basis": "S5 NOT_AUTHORISED"}],
        },
        "host:genie-adapter": {
            "dir": "host_genie-adapter",
            "entry_file": "object-crosswalk.json",
            "entry_kind": "object_crosswalk",
            "loader": "object_crosswalk_v1",
            "source_objects": ["S0:GENIEProjectionRef", "S0:ArtifactIdentity", "S0:ProfileBinding",
                               "S0:PI-PKG", "S0:PD-PKG", "SEAM:S6", "ADAPTER:MAPPING"],
            "field_contract_sources": ["S0:GENIEProjectionRef", "S0:ArtifactIdentity"],
            "required_mappings": ["S0:PD-PKG", "S0:ProfileBinding", "S0:PI-PKG",
                                  "S0:ArtifactIdentity"],
            "required_targets_from": "S0:GENIEProjectionRef",
            "allowed_permissions": ["read:canonical-objects", "emit:projection",
                                    "emit:object-crosswalk"],
            "provider": {"provider_id": "genie-live-integration", "admission_state": "OFF",
                         "live_integration": False,
                         "basis": "S6 GENIE live integration NOT_AUTHORISED"},
            "compatibility_source": "SEAM:S6",
            "capability_loss": [
                {"record_type": "CapabilityLoss", "loss_id": "LOSS-GA-01",
                 "capability": "truth writeback",
                 "reason": "GENIE target refs are reference-only; no truth writeback by contract",
                 "severity": "DECLARED"},
                {"record_type": "CapabilityLoss", "loss_id": "LOSS-GA-02",
                 "capability": "live GENIE integration",
                 "reason": "S6 GENIE live integration NOT_AUTHORISED; seam schema only",
                 "severity": "DECLARED"}],
            "nack": [
                {"record_type": "NACK", "nack_id": "NACK-GA-01",
                 "statement": "object-crosswalk effective load is a fixture/mock contract load, not a live GENIE run",
                 "basis": "S6 NOT_AUTHORISED"},
                {"record_type": "NACK", "nack_id": "NACK-GA-02",
                 "statement": "no live GENIE integration PASS is claimed by this projection",
                 "basis": "S6 NOT_AUTHORISED"}],
        },
    },
}

WEB_DOC_FILES = ("PIPD_BOOTSTRAP.md", "PIPD_CANONICAL_CORE.md", "PIPD_ROUTER_PROFILES.md",
                 "PIPD_ARTIFACT_SCHEMAS.md", "PIPD_EVAL_HANDOFF.md")

WEB_DOC_SPECS: dict[str, dict[str, Any]] = {
    "PIPD_BOOTSTRAP": {
        "file": "PIPD_BOOTSTRAP.md",
        "title": "PIPD-LS-SP Bootstrap",
        "source_objects": "ALL",
    },
    "PIPD_CANONICAL_CORE": {
        "file": "PIPD_CANONICAL_CORE.md",
        "title": "PIPD Canonical Core Objects",
        "source_objects": ["REGISTRY:CONTRACT-FAMILIES", "S0:*"],
    },
    "PIPD_ROUTER_PROFILES": {
        "file": "PIPD_ROUTER_PROFILES.md",
        "title": "PIPD Router Profiles",
        "source_objects": ["PROFILE:TRIO", "ADAPTER:MAPPING"],
    },
    "PIPD_ARTIFACT_SCHEMAS": {
        "file": "PIPD_ARTIFACT_SCHEMAS.md",
        "title": "PIPD Artifact Schemas",
        "source_objects": ["S0:*"],
    },
    "PIPD_EVAL_HANDOFF": {
        "file": "PIPD_EVAL_HANDOFF.md",
        "title": "PIPD Evaluation Handoff",
        "source_objects": ["SEAM:S5", "SEAM:S6", "SEAM:S7", "SEAM:S8", "ADAPTER:MAPPING",
                           "PROFILE:TRIO", "S0:ClaimCeiling", "S0:TQAEP",
                           "S0:EvidenceExpectation"],
    },
}

WEB_CAPABILITY_LOSS = (
    {"record_type": "CapabilityLoss", "loss_id": "LOSS-WEB-01",
     "capability": "runtime authority",
     "reason": "the Web pack is a read-only semantic surface; it executes nothing",
     "severity": "DECLARED"},
)
WEB_NACK = (
    {"record_type": "NACK", "nack_id": "NACK-WEB-01",
     "statement": "this document carries contracts and provenance only; it has no runtime effect",
     "basis": "claim ceiling: DESIGN/FILE_PRESENT/SCHEMA_VALID only"},
    {"record_type": "NACK", "nack_id": "NACK-WEB-02",
     "statement": "no live HGK/GENIE integration PASS is claimed; S5/S6 seams are fixture/mock only",
     "basis": "S5/S6 NOT_AUTHORISED"},
)

CLAIMS = {
    "live_hgk_genie_integration": "NOT_CLAIMED",
    "s5_s6": "NOT_AUTHORISED",
    "adapter_checks": "FIXTURE_MOCK_ONLY",
    "live_status": "NOT_RUN",
}


# ---------------------------------------------------------------- typed records

@dataclass(frozen=True)
class SourceRef:
    object_id: str
    schema: str
    schema_version: str
    source_path: str
    source_hash: str

    def to_json(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class CapabilityLossRecord:
    record_type: str
    loss_id: str
    capability: str
    reason: str
    severity: str

    def to_json(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class NackRecord:
    record_type: str
    nack_id: str
    statement: str
    basis: str

    def to_json(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class ArtifactIR:
    artifact_id: str
    kind: str
    path: str
    denominator: bool
    source_objects: tuple[SourceRef, ...]
    source_hash: str
    capability_loss: tuple[CapabilityLossRecord, ...]
    nack: tuple[NackRecord, ...]
    scope: tuple[str, ...]
    payload: Any

    def to_json(self) -> dict:
        return {
            "artifact_id": self.artifact_id,
            "kind": self.kind,
            "path": self.path,
            "denominator": self.denominator,
            "source_objects": [s.to_json() for s in self.source_objects],
            "source_hash": self.source_hash,
            "capability_loss": [c.to_json() for c in self.capability_loss],
            "nack": [n.to_json() for n in self.nack],
            "scope": list(self.scope),
            "payload": self.payload,
        }


SOURCE_REF_FIELDS = ("object_id", "schema", "schema_version", "source_path", "source_hash")
LOSS_FIELDS = ("record_type", "loss_id", "capability", "reason", "severity")
NACK_FIELDS = ("record_type", "nack_id", "statement", "basis")
ARTIFACT_FIELDS = ("artifact_id", "kind", "path", "denominator", "source_objects",
                   "source_hash", "capability_loss", "nack", "scope", "payload")
IR_FIELDS = ("schema", "schema_version", "profile", "adapter_mapping", "source_index",
             "artifacts", "projection_parity_sha256")
HOST_RECORD_FIELDS = ("schema", "schema_version", "surface", "entry_kind", "contract_version",
                      "field_contract", "source_refs", "compatibility", "capability_loss",
                      "nack", "provider", "permissions", "scope", "payload")

ALLOWED_SCOPE = tuple(ADAPTER_MAPPING["writable_scope"])


# ---------------------------------------------------------------- canonical sources

def _ref(object_id: str, schema: str, version: str, path: str, digest: str) -> SourceRef:
    return SourceRef(object_id, schema, version, path, digest)


def load_canonical_objects(root: Path) -> dict[str, Any]:
    """Load the canonical PIPD objects from `root`: registry + schema files, the
    profile trio, and the S5-S8 seam fixtures. Pure reads."""
    root = Path(root)
    objects: dict[str, SourceRef] = {}
    raw: dict[str, Any] = {}
    order: list[str] = []

    def add(ref: SourceRef, payload: Any) -> None:
        objects[ref.object_id] = ref
        raw[ref.object_id] = payload
        order.append(ref.object_id)

    reg_path = root / "schemas" / "registry.json"
    registry = json.loads(reg_path.read_text(encoding="utf-8"))
    add(_ref("REGISTRY:CONTRACT-FAMILIES", registry.get("schema", "PIPD-S0-CONTRACT-REGISTRY/1"),
             "1", "schemas/registry.json", sha256_file(reg_path)), registry)

    families = []
    for fam in registry.get("families", []):
        rel = fam["schema_file"]
        spath = root / rel
        schema = json.loads(spath.read_text(encoding="utf-8"))
        sid = schema.get("$id", "")
        version = sid.rsplit(":", 1)[-1] if sid else "0"
        add(_ref(f"S0:{fam['contract']}", sid, version, rel, sha256_file(spath)),
            {"family": fam, "schema": schema})
        families.append(fam["contract"])

    prof_path = root / "src" / "pipd_ls_sp" / "profiles.py"
    prof_text = prof_path.read_text(encoding="utf-8")
    vals: dict[str, Any] = {}
    for node in ast.parse(prof_text).body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id in ("PROFILES", "AXES"):
                    vals[target.id] = ast.literal_eval(node.value)
    if "PROFILES" not in vals or "AXES" not in vals:
        raise MissingField("profiles.py must define PROFILES and AXES")
    add(_ref("PROFILE:TRIO", "PIPD-PROFILE-TRIO/1", "1", "src/pipd_ls_sp/profiles.py",
             sha256_file(prof_path)), vals)

    seams = {}
    for stage in ("s5", "s6", "s7", "s8"):
        rel = f"fixtures/s5_s8/{stage}_compat.json"
        spath = root / rel
        fixture = json.loads(spath.read_text(encoding="utf-8"))
        seams[stage.upper()] = fixture
        add(_ref(f"SEAM:{stage.upper()}", "PIPD-SEAM-COMPAT/1", "1", rel, sha256_file(spath)),
            fixture)

    adapter_ref = _ref("ADAPTER:MAPPING", "PIPD-ADAPTER-MAPPING/1", "1",
                       "src/pipd_ls_sp/projection.py#ADAPTER_MAPPING",
                       sha256_text(canonical_json(ADAPTER_MAPPING)))
    add(adapter_ref, ADAPTER_MAPPING)

    return {"objects": objects, "raw": raw, "order": order, "registry": registry,
            "profiles": vals, "seams": seams, "root": root}


def _aggregate_hash(refs: list[SourceRef] | tuple[SourceRef, ...]) -> str:
    return sha256_text(canonical_json([r.to_json() for r in refs]))


# ---------------------------------------------------------------- IR compilation

def _schema_props(entry: dict) -> tuple[list[dict], list[str]]:
    """Field contract rows derived from a canonical schema object."""
    schema = entry["schema"]
    required = list(schema.get("required", []))
    rows = []
    for name in schema.get("properties", {}):
        spec = schema.get("properties", {}).get(name) or {}
        dtype = spec.get("type", "object") if isinstance(spec, dict) else "object"
        if dtype not in TYPE_VOCAB:
            dtype = "object"
        rows.append({"name": name, "type": dtype, "required": name in required})
    return rows, required


def _derive_field_contract(canon: dict, host_spec: dict) -> list[dict]:
    rows: list[dict] = []
    seen: dict[str, int] = {}
    for oid in host_spec["field_contract_sources"]:
        entry = canon["raw"].get(oid)
        if not isinstance(entry, dict) or "schema" not in entry:
            raise MissingField(f"field contract source {oid} is not a canonical schema object")
        prop_rows, _ = _schema_props(entry)
        for row in prop_rows:
            row = dict(row)
            row["source_object_id"] = oid
            if row["name"] in seen:
                prev = rows[seen[row["name"]]]
                prev["required"] = prev["required"] or row["required"]
            else:
                seen[row["name"]] = len(rows)
                rows.append(row)
    return rows


def _compatibility(canon: dict, host_spec: dict) -> dict:
    source = host_spec.get("compatibility_source")
    if source and source in canon["raw"]:
        fixture = canon["raw"][source]
        return {"mode": "FIXTURE_MOCK",
                "fixture_kind": fixture.get("fixture_kind", "compatibility"),
                "live_status": fixture.get("live_status", "NOT_RUN"),
                "seam_schemas": list(fixture.get("seam_schemas", [])),
                "seam_source": source,
                "asserted": dict(fixture.get("asserted", {}))}
    return {"mode": "FIXTURE_MOCK", "fixture_kind": "compatibility",
            "live_status": "NOT_RUN",
            "seam_schemas": ["SurfaceProjectionManifest", "ProfileBinding"],
            "seam_source": "ADAPTER:MAPPING",
            "asserted": {"itch_contract_only": True, "no_live_receiver_ack": True,
                         "no_world_effect": True}}


def _host_record(canon: dict, surface: str) -> dict:
    host_spec = ADAPTER_MAPPING["hosts"][surface]
    refs = [canon["objects"][oid].to_json() for oid in host_spec["source_objects"]]
    field_contract = _derive_field_contract(canon, host_spec)
    payload = _host_payload(canon, surface, host_spec)
    record = {
        "schema": SCHEMA_HOST_RECORD,
        "schema_version": SCHEMA_VERSION,
        "surface": surface,
        "entry_kind": host_spec["entry_kind"],
        "contract_version": SCHEMA_VERSION,
        "field_contract": field_contract,
        "source_refs": refs,
        "compatibility": _compatibility(canon, host_spec),
        "capability_loss": [dict(r) for r in host_spec["capability_loss"]],
        "nack": [dict(r) for r in host_spec["nack"]],
        "provider": dict(host_spec["provider"]),
        "permissions": list(host_spec["allowed_permissions"]),
        "scope": list(ALLOWED_SCOPE),
        "payload": payload,
    }
    return record


def _host_payload(canon: dict, surface: str, host_spec: dict) -> dict:
    if host_spec["entry_kind"] == "skill_projection":
        return {
            "skill_id": host_spec["skill_id"],
            "input_object_id": "S0:SurfaceProjectionManifest",
            "output_object_id": "S0:ProfileBinding",
            "contract_refs": list(host_spec["source_objects"]),
            "trigger": [
                "user asks to project canonical PIPD objects onto Web or host surfaces",
                "a surface pack or host projection must be (re)generated from canonical sources",
            ],
            "non_trigger": [
                "live HGK execution or GENIE integration requests (S5/S6 NOT_AUTHORISED)",
                "requirement compilation or pipeline entry points (owned by another lane)",
            ],
        }
    if host_spec["entry_kind"] == "receiver_map":
        receivers = []
        for oid in host_spec["required_mappings"]:
            entry = canon["raw"][oid]
            rows, _ = _schema_props(entry)
            receivers.append({
                "receiver_id": "hgk." + oid.split(":", 1)[1].lower().replace("-", "."),
                "source_object_id": oid,
                "entry": "receive_" + oid.split(":", 1)[1].lower().replace("-", "_"),
                "ack_state": "NACK_ONLY",
                "fields": [{"name": r["name"], "type": r["type"], "required": r["required"]}
                           for r in rows],
            })
        return {"abi_version": "PIPD-HGK-RECEIVER-ABI/1", "receivers": receivers}
    if host_spec["entry_kind"] == "object_crosswalk":
        targets = _required_targets(canon, host_spec)
        target_sources = {
            "ProductGraph": "S0:PD-PKG",
            "Profile": "S0:ProfileBinding",
            "Bundle": "S0:PI-PKG",
            "GENIEArtifact": "S0:ArtifactIdentity",
        }
        mappings = []
        for target in targets:
            oid = target_sources[target]
            ref = canon["objects"][oid]
            mappings.append({
                "source_object_id": oid,
                "source_schema": ref.schema,
                "source_version": ref.schema_version,
                "target": target,
                "target_ref": f"urn:genie:seam:{target}",
                "direction": "REFERENCE_ONLY",
            })
        return {"crosswalk_version": "PIPD-GENIE-CROSSWALK/1",
                "required_targets": targets, "mappings": mappings}
    raise UnsupportedSurface(f"unknown entry kind {host_spec['entry_kind']!r}")


def _required_targets(canon: dict, host_spec: dict) -> list[str]:
    oid = host_spec.get("required_targets_from")
    if not oid:
        return []
    entry = canon["raw"].get(oid)
    if not isinstance(entry, dict):
        raise MissingField(f"required target source {oid} missing")
    schema = entry["schema"]
    targets = list(schema.get("properties", {}).get("target_refs", {}).get("required", []))
    if not targets:
        raise MissingField(f"{oid} declares no required target_refs")
    return targets


def _resolve_doc_sources(canon: dict, spec_key: str) -> list[str]:
    spec = WEB_DOC_SPECS[spec_key]["source_objects"]
    if spec == "ALL":
        return list(canon["order"])
    out = []
    for oid in spec:
        if oid == "S0:*":
            out.extend(o for o in canon["order"] if o.startswith("S0:"))
        else:
            out.append(oid)
    return out


def _doc_payload(canon: dict, doc_id: str) -> dict:
    """Sections compiled from canonical data — no free text."""
    reg = canon["registry"]
    profiles = canon["profiles"]
    if doc_id == "PIPD_BOOTSTRAP":
        inv = [[oid, canon["objects"][oid].schema, canon["objects"][oid].schema_version,
                canon["objects"][oid].source_path, canon["objects"][oid].source_hash]
               for oid in canon["order"]]
        hosts = [[surface, spec["dir"], spec["entry_file"], spec["loader"],
                  spec["provider"]["admission_state"],
                  "false" if not spec["provider"]["live_integration"] else "true"]
                 for surface, spec in ADAPTER_MAPPING["hosts"].items()]
        denom = [["PIPD_BOOTSTRAP.md..PIPD_EVAL_HANDOFF.md", "WEB_DOC", "5", "true"],
                 [UI_DIR + "/" + ", ".join(UI_FILES), UI_KIND, "5", "false"]]
        routing = [[profile, ", ".join(surfaces)]
                   for profile, surfaces in sorted(ADAPTER_MAPPING["routing"].items())]
        return {"sections": [
            {"heading": "Canonical Source Inventory",
             "columns": ["object_id", "schema", "schema_version", "source_path", "source_hash"],
             "rows": inv},
            {"heading": "Host Surfaces",
             "columns": ["surface", "dir", "entry_file", "loader", "provider_admission_state",
                         "live_integration"],
             "rows": hosts},
            {"heading": "Web Denominator",
             "columns": ["files", "kind", "count", "in_denominator"],
             "rows": denom},
            {"heading": "Profile Routing",
             "columns": ["profile", "host_surfaces"],
             "rows": routing},
        ]}
    if doc_id == "PIPD_CANONICAL_CORE":
        fam_rows = [[f["index"], f["contract"], f["owner"], ", ".join(f.get("consumers", [])),
                     f.get("materialization", ""), f.get("schema_file", "")]
                    for f in reg.get("families", [])]
        reg_rows = [[f["contract"], ", ".join(f.get("required_fields", []))]
                    for f in reg.get("families", [])]
        schema_rows = []
        for oid in canon["order"]:
            if not oid.startswith("S0:"):
                continue
            entry = canon["raw"][oid]
            schema = entry["schema"]
            schema_rows.append([oid, schema.get("$id", ""), schema.get("$schema", ""),
                                ", ".join(schema.get("required", []))])
        return {"sections": [
            {"heading": "Contract Families",
             "columns": ["index", "contract", "owner", "consumers", "materialization",
                         "schema_file"],
             "rows": fam_rows},
            {"heading": "Required Fields — Registry Declaration",
             "columns": ["contract", "required_fields"],
             "rows": reg_rows},
            {"heading": "Required Fields — Schema Declaration",
             "columns": ["object_id", "schema_id", "schema_draft", "required_fields"],
             "rows": schema_rows},
        ]}
    if doc_id == "PIPD_ROUTER_PROFILES":
        prof_rows = [[name, cfg["artifact_depth"], ", ".join(cfg["assurance"]),
                      cfg["target_resolution"], str(cfg["max_axes"])]
                     for name, cfg in sorted(profiles["PROFILES"].items())]
        axis_rows = [[axis] for axis in profiles["AXES"]]
        route_rows = [[profile, surface, ADAPTER_MAPPING["hosts"][surface]["entry_kind"]]
                      for profile, surfaces in sorted(ADAPTER_MAPPING["routing"].items())
                      for surface in surfaces]
        bind_rows = [["PROFILE:TRIO", canon["objects"]["PROFILE:TRIO"].schema,
                      canon["objects"]["PROFILE:TRIO"].schema_version,
                      canon["objects"]["PROFILE:TRIO"].source_hash],
                     ["ADAPTER:MAPPING", canon["objects"]["ADAPTER:MAPPING"].schema,
                      canon["objects"]["ADAPTER:MAPPING"].schema_version,
                      canon["objects"]["ADAPTER:MAPPING"].source_hash]]
        return {"sections": [
            {"heading": "Profile Trio",
             "columns": ["profile", "artifact_depth", "assurance", "target_resolution",
                         "max_axes"],
             "rows": prof_rows},
            {"heading": "Router Axes",
             "columns": ["axis"],
             "rows": axis_rows},
            {"heading": "Router Matrix",
             "columns": ["profile", "host_surface", "entry_kind"],
             "rows": route_rows},
            {"heading": "Profile Binding Sources",
             "columns": ["object_id", "schema", "schema_version", "source_hash"],
             "rows": bind_rows},
        ]}
    if doc_id == "PIPD_ARTIFACT_SCHEMAS":
        rows = []
        for oid in canon["order"]:
            if not oid.startswith("S0:"):
                continue
            entry = canon["raw"][oid]
            schema = entry["schema"]
            rows.append([oid, schema.get("$id", ""), schema.get("$schema", ""),
                         "true" if schema.get("additionalProperties") else "false",
                         ", ".join(schema.get("required", [])),
                         ", ".join(schema.get("properties", {}))])
        return {"sections": [
            {"heading": "Schema Contracts",
             "columns": ["object_id", "schema_id", "schema_draft", "additional_properties",
                         "required_fields", "properties"],
             "rows": rows},
        ]}
    if doc_id == "PIPD_EVAL_HANDOFF":
        seam_rows = []
        for stage in ("s5", "s6", "s7", "s8"):
            fixture = canon["seams"][stage.upper()]
            seam_rows.append([fixture.get("stage", stage.upper()),
                              ", ".join(fixture.get("seam_schemas", [])),
                              fixture.get("fixture_kind", ""),
                              fixture.get("live_status", ""),
                              canonical_json(fixture.get("asserted", {}))])
        oracle_rows = [[oid, canon["objects"][oid].schema,
                        canon["objects"][oid].schema_version, canon["objects"][oid].source_hash]
                       for oid in ("S0:ClaimCeiling", "S0:TQAEP", "S0:EvidenceExpectation")]
        gate_rows = [["G-S3-WEB", "tools/web_pack_check.py --strict", "STRICT_CHECK_ONLY",
                      "five PIPD documents; OPTIONAL_SITE_UI excluded"],
                     ["G-S3-HOST", "tools/host_projection_check.py --strict", "STRICT_CHECK_ONLY",
                      "three host effective loads; fixture/mock only"]]
        assurance_rows = [[name, ", ".join(cfg["assurance"])]
                          for name, cfg in sorted(profiles["PROFILES"].items())]
        claim_rows = [[k, v] for k, v in sorted(CLAIMS.items())]
        return {"sections": [
            {"heading": "Seam Compatibility Fixtures",
             "columns": ["stage", "seam_schemas", "fixture_kind", "live_status", "asserted"],
             "rows": seam_rows},
            {"heading": "Eval Oracle Objects",
             "columns": ["object_id", "schema", "schema_version", "source_hash"],
             "rows": oracle_rows},
            {"heading": "Gate Entrypoints",
             "columns": ["gate", "command", "mode", "denominator"],
             "rows": gate_rows},
            {"heading": "Profile Assurance",
             "columns": ["profile", "assurance"],
             "rows": assurance_rows},
            {"heading": "Claim Ceiling",
             "columns": ["claim", "state"],
             "rows": claim_rows},
        ]}
    raise MissingField(f"unknown web doc {doc_id!r}")


def compile_projection_ir(root: Path) -> dict[str, Any]:
    """Compile the typed projection IR from canonical objects + profile + adapter mapping."""
    canon = load_canonical_objects(root)
    artifacts: list[dict] = []

    def source_refs(oids: list[str]) -> list[SourceRef]:
        return [canon["objects"][oid] for oid in oids]

    for doc_id, spec in WEB_DOC_SPECS.items():
        refs = source_refs(_resolve_doc_sources(canon, doc_id))
        payload = _doc_payload(canon, doc_id)
        payload["doc_id"] = doc_id
        payload["title"] = spec["title"]
        art = ArtifactIR(
            artifact_id=f"web:{doc_id}",
            kind=WEB_DOC_KIND,
            path=spec["file"],
            denominator=True,
            source_objects=tuple(refs),
            source_hash=_aggregate_hash(refs),
            capability_loss=tuple(CapabilityLossRecord(**r) for r in WEB_CAPABILITY_LOSS),
            nack=tuple(NackRecord(**r) for r in WEB_NACK),
            scope=ALLOWED_SCOPE,
            payload=payload,
        )
        artifacts.append(art.to_json())

    for surface, host_spec in ADAPTER_MAPPING["hosts"].items():
        record = _host_record(canon, surface)
        refs = source_refs(host_spec["source_objects"])
        art = ArtifactIR(
            artifact_id=f"host:{surface}",
            kind=HOST_KIND,
            path=f"{host_spec['dir']}/{host_spec['entry_file']}",
            denominator=False,
            source_objects=tuple(refs),
            source_hash=_aggregate_hash(refs),
            capability_loss=tuple(CapabilityLossRecord(**r) for r in host_spec["capability_loss"]),
            nack=tuple(NackRecord(**r) for r in host_spec["nack"]),
            scope=ALLOWED_SCOPE,
            payload=record,
        )
        artifacts.append(art.to_json())

    ui_refs = [canon["objects"]["ADAPTER:MAPPING"]]
    ui_payload = {"category": UI_KIND, "excluded_from_web_denominator": True,
                  "files": list(UI_FILES), "web_denominator": WEB_DOC_FILES}
    art = ArtifactIR(
        artifact_id="ui:OPTIONAL_SITE_UI",
        kind=UI_KIND,
        path=f"{UI_DIR}/",
        denominator=False,
        source_objects=tuple(ui_refs),
        source_hash=_aggregate_hash(ui_refs),
        capability_loss=(CapabilityLossRecord(
            record_type="CapabilityLoss", loss_id="LOSS-UI-01",
            capability="semantic document status",
            reason="site UI five files are OPTIONAL_SITE_UI and carry no PIPD semantic contract",
            severity="DECLARED"),),
        nack=(NackRecord(
            record_type="NACK", nack_id="NACK-UI-01",
            statement="OPTIONAL_SITE_UI files are excluded from the Web denominator and cannot pass G-S3-WEB",
            basis="R-AUD-003"),),
        scope=ALLOWED_SCOPE,
        payload=ui_payload,
    )
    artifacts.append(art.to_json())

    ir = {
        "schema": SCHEMA_IR,
        "schema_version": SCHEMA_VERSION,
        "profile": {"profiles": canon["profiles"]["PROFILES"], "axes": list(canon["profiles"]["AXES"]),
                    "routing": ADAPTER_MAPPING["routing"]},
        "adapter_mapping": ADAPTER_MAPPING,
        "source_index": [canon["objects"][oid].to_json() for oid in canon["order"]],
        "artifacts": artifacts,
    }
    ir["projection_parity_sha256"] = _parity_hash(ir)
    return ir


def _parity_hash(ir: dict) -> str:
    rows = sorted([[a["artifact_id"], a["path"], a["source_hash"],
                    sha256_text(canonical_json(a["payload"]))] for a in ir["artifacts"]])
    return sha256_text(canonical_json(rows))


# ---------------------------------------------------------------- IR validation

def validate_projection_ir(ir: dict) -> dict:
    """Refuse empty payloads, missing fields and scope widening (R-AUD-015 negatives)."""
    if not isinstance(ir, dict):
        raise MissingField("projection IR must be an object")
    for key in IR_FIELDS:
        if key not in ir:
            raise MissingField(f"projection IR missing {key}")
    if ir["schema"] != SCHEMA_IR:
        raise MissingField(f"projection IR schema {ir['schema']!r} != {SCHEMA_IR}")
    artifacts = ir["artifacts"]
    if not isinstance(artifacts, list) or not artifacts:
        raise EmptyPayload("projection IR carries no artifacts")
    for art in artifacts:
        for key in ARTIFACT_FIELDS:
            if key not in art:
                raise MissingField(f"artifact {art.get('artifact_id', '?')} missing {key}")
        if art["kind"] not in (WEB_DOC_KIND, HOST_KIND, UI_KIND):
            raise UnsupportedSurface(f"artifact {art['artifact_id']} has unknown kind {art['kind']!r}")
        if not isinstance(art["payload"], (dict, list, str)) or not art["payload"]:
            raise EmptyPayload(f"artifact {art['artifact_id']} has an empty payload")
        for scope_entry in art["scope"]:
            if scope_entry not in ALLOWED_SCOPE:
                raise ScopeWidening(
                    f"artifact {art['artifact_id']} widens scope to {scope_entry!r}")
        refs = art["source_objects"]
        if not isinstance(refs, list) or not refs:
            raise MissingField(f"artifact {art['artifact_id']} has no source objects")
        for ref in refs:
            for key in SOURCE_REF_FIELDS:
                if key not in ref or not ref[key]:
                    raise MissingField(
                        f"artifact {art['artifact_id']} source ref missing {key}")
        computed = _aggregate_hash([SourceRef(**r) for r in refs])
        if art["source_hash"] != computed:
            raise StaleSource(f"artifact {art['artifact_id']} source hash does not match sources")
        for rec, fields, kind_name in ((art["capability_loss"], LOSS_FIELDS, "CapabilityLoss"),
                                       (art["nack"], NACK_FIELDS, "NACK")):
            if not isinstance(rec, list) or not rec:
                raise EmptyPayload(f"artifact {art['artifact_id']} has no {kind_name} record")
            for item in rec:
                for key in fields:
                    if key not in item or item[key] in (None, ""):
                        raise MissingField(
                            f"artifact {art['artifact_id']} {kind_name} record missing {key}")
        if art["kind"] == HOST_KIND:
            record = art["payload"]
            if not isinstance(record, dict):
                raise MissingField(f"host artifact {art['artifact_id']} payload is not a record")
            if not record.get("source_refs"):
                raise MarkerOnlyStub(f"host artifact {art['artifact_id']} is a marker-only stub")
            if not record.get("field_contract"):
                raise MarkerOnlyStub(f"host artifact {art['artifact_id']} has no field contract")
    return ir


# ---------------------------------------------------------------- renderers

def _table(columns: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(columns) + " |",
             "| " + " | ".join("---" for _ in columns) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(lines)


def _meta_block(meta: dict) -> str:
    return ("<!--PIPD-DOC-META\n"
            + json.dumps(meta, ensure_ascii=False, indent=1, sort_keys=True)
            + "\n-->")


def _doc_meta(art: dict) -> dict:
    return {
        "schema": SCHEMA_DOC_META,
        "schema_version": SCHEMA_VERSION,
        "doc_id": art["payload"]["doc_id"],
        "kind": art["kind"],
        "denominator": art["denominator"],
        "source_objects": art["source_objects"],
        "source_hash": art["source_hash"],
        "capability_loss": art["capability_loss"],
        "nack": art["nack"],
        "scope": list(art["scope"]),
    }


def render_web_doc(art: dict) -> str:
    payload = art["payload"]
    out = [f"# {payload['title']}", "", _meta_block(_doc_meta(art)), ""]
    out += ["## Source Objects", "",
            _table(["object_id", "schema", "schema_version", "source_path", "source_hash"],
                   [[r["object_id"], r["schema"], r["schema_version"], r["source_path"],
                     r["source_hash"]] for r in art["source_objects"]]), ""]
    out += ["## Capability Loss", "",
            _table(["loss_id", "record_type", "capability", "reason", "severity"],
                   [[r["loss_id"], r["record_type"], r["capability"], r["reason"], r["severity"]]
                    for r in art["capability_loss"]]), ""]
    out += ["## NACK", "",
            _table(["nack_id", "record_type", "statement", "basis"],
                   [[r["nack_id"], r["record_type"], r["statement"], r["basis"]]
                    for r in art["nack"]]), ""]
    for section in payload["sections"]:
        out += [f"## {section['heading']}", "",
                _table(section["columns"], section["rows"]), ""]
    return "\n".join(out)


def _record_block(record: dict) -> str:
    return ("<!--PIPD-HOST-RECORD\n"
            + json.dumps(record, ensure_ascii=False, indent=1, sort_keys=True)
            + "\n-->")


def render_host_entry(record: dict) -> str:
    if record["entry_kind"] == "skill_projection":
        skill = record["payload"]
        out = ["---", f"name: {skill['skill_id']}",
               "description: Project canonical PIPD objects, profiles and the adapter mapping "
               "onto Web and host surfaces with declared capability loss. Fixture/mock contract "
               "only; S5/S6 NOT_AUTHORISED.", "---", "",
               f"# {skill['skill_id']}", "", _record_block(record), "",
               "## Contract", "",
               _table(["field", "type", "required", "source_object_id"],
                      [[r["name"], r["type"], "true" if r["required"] else "false",
                        r["source_object_id"]] for r in record["field_contract"]]), "",
               _table(["role", "object_id"],
                      [["input", skill["input_object_id"]], ["output", skill["output_object_id"]]]
                      + [["contract_ref", oid] for oid in skill["contract_refs"]]), "",
               "## Trigger", ""]
        out += [f"- {line}" for line in skill["trigger"]]
        out += ["", "## Non-Trigger", ""]
        out += [f"- {line}" for line in skill["non_trigger"]]
        out += ["", "## Capability Loss", "",
                _table(["loss_id", "capability", "reason", "severity"],
                       [[r["loss_id"], r["capability"], r["reason"], r["severity"]]
                        for r in record["capability_loss"]]), "",
                "## NACK", "",
                _table(["nack_id", "statement", "basis"],
                       [[r["nack_id"], r["statement"], r["basis"]]
                        for r in record["nack"]]), ""]
        return "\n".join(out)
    return json.dumps(record, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def render_ui_file(name: str) -> str:
    marker = ("OPTIONAL_SITE_UI: excluded from the Web denominator (R-AUD-003). "
              "The Web pack is the five PIPD_*.md documents.")
    if name == "index.html":
        return ("<!doctype html><meta charset=utf-8><title>PIPD-LS-SP OPTIONAL_SITE_UI</title>\n"
                f"<!-- {marker} -->\n<div id=app></div><script src=app.js></script>\n")
    if name == "app.js":
        return ("// " + marker + "\n"
                "fetch('PROJECTION_IR.json').then(r => r.json()).then(ir => {"
                "document.getElementById('app').textContent = "
                "'PIPD-LS-SP OPTIONAL_SITE_UI ' + ir.projection_parity_sha256;});\n")
    if name == "styles.css":
        return "/* " + marker + " */\nbody{font-family:system-ui;margin:2rem}\n"
    if name == "manifest.webmanifest":
        return json.dumps({"name": "PIPD-LS-SP OPTIONAL_SITE_UI", "short_name": "PIPD-UI",
                           "version": "0.1.0", "category": UI_KIND,
                           "excluded_from_web_denominator": True},
                          ensure_ascii=False, indent=1, sort_keys=True) + "\n"
    if name == "README.md":
        return ("# OPTIONAL_SITE_UI\n\n" + marker + "\n\n"
                "These five files are a site UI pack: `index.html`, `app.js`, `styles.css`, "
                "`manifest.webmanifest`, `README.md`. They are NOT the PIPD Web documents and "
                "are never counted in the Web denominator.\n")
    raise MissingField(f"unknown UI file {name!r}")


# ---------------------------------------------------------------- generation

def project_surfaces(root: Path, out: Path) -> dict[str, Any]:
    """Regenerate the whole projection surface from canonical sources.

    `out` is a generated surface: regeneration replaces it wholesale, so a
    stale source is always regenerated and no leak survives. The output is
    deterministic for a given source state (byte-for-byte replayable)."""
    ir = compile_projection_ir(root)
    validate_projection_ir(ir)
    out = Path(out)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    web_files = []
    for art in ir["artifacts"]:
        if art["kind"] == WEB_DOC_KIND:
            (out / art["path"]).write_text(render_web_doc(art), encoding="utf-8", newline="")
            web_files.append(art["path"])
        elif art["kind"] == HOST_KIND:
            d = out / Path(art["path"]).parent
            d.mkdir(parents=True, exist_ok=True)
            (d / Path(art["path"]).name).write_text(
                render_host_entry(art["payload"]), encoding="utf-8", newline="")
    (out / IR_FILE).write_text(
        json.dumps(ir, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
        encoding="utf-8", newline="")
    ui_dir = out / UI_DIR
    ui_dir.mkdir(parents=True, exist_ok=True)
    for name in UI_FILES:
        (ui_dir / name).write_text(render_ui_file(name), encoding="utf-8", newline="")

    return {"verdict": "PASS", "out": str(out), "web_pack": sorted(web_files),
            "web_count": f"{len(web_files)}/5",
            "hosts": {surface: spec["dir"] for surface, spec in ADAPTER_MAPPING["hosts"].items()},
            "optional_site_ui": {"files": list(UI_FILES), "denominator": False},
            "projection_parity_sha256": ir["projection_parity_sha256"]}


# ---------------------------------------------------------------- checks

_META_RE = re.compile(r"<!--PIPD-DOC-META\s*\n(.*?)\n-->", re.S)
_RECORD_RE = re.compile(r"<!--PIPD-HOST-RECORD\s*\n(.*?)\n-->", re.S)
_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.S)


def _fail(code_exc: type[ProjectionError], reason: str, path: str) -> dict:
    return {"code": code_exc.code, "mutation": code_exc.mutation,
            "reason": reason, "path": path}


def _check_record_common(record: dict, expected: dict, path: str, failures: list) -> None:
    """Field-level contract / source refs / compatibility / loss / provider / permission /
    scope checks shared by every host loader. `record` is what is on disk."""
    for key in HOST_RECORD_FIELDS:
        if key not in record:
            failures.append(_fail(MissingField, f"host record missing {key}", path))
            return
    surface = record["surface"]
    if surface not in ADAPTER_MAPPING["hosts"]:
        failures.append(_fail(UnsupportedHost, f"unsupported host surface {surface!r}", path))
        return
    if record["entry_kind"] != ADAPTER_MAPPING["hosts"][surface]["entry_kind"]:
        failures.append(_fail(MissingField,
                              f"entry kind {record['entry_kind']!r} does not match adapter mapping",
                              path))
    expected_contract = expected["field_contract"]
    if not record["field_contract"]:
        failures.append(_fail(MarkerOnlyStub, "field-level contract is empty", path))
    elif record["field_contract"] != expected_contract:
        missing = [r["name"] for r in expected_contract
                   if r not in record["field_contract"]]
        failures.append(_fail(MissingField,
                              f"field contract does not match derived contract; missing {missing}",
                              path))
    if not record["source_refs"]:
        failures.append(_fail(MarkerOnlyStub, "no source references", path))
    known = set(load_canonical_objects_cache["objects"])
    for ref in record["source_refs"]:
        for key in SOURCE_REF_FIELDS:
            if key not in ref or not ref[key]:
                failures.append(_fail(MissingField, f"source ref missing {key}", path))
                break
        else:
            if ref["object_id"] not in known:
                failures.append(_fail(UnknownSourceObject,
                                      f"unknown source object {ref['object_id']!r}", path))
            elif ref["source_hash"] != load_canonical_objects_cache["objects"][ref["object_id"]].source_hash:
                failures.append(_fail(StaleSource,
                                      f"stale source hash for {ref['object_id']}", path))
    compat = record["compatibility"]
    if not isinstance(compat, dict) or "mode" not in compat or "live_status" not in compat:
        failures.append(_fail(MissingField, "compatibility record missing", path))
    else:
        if compat.get("live_status") != "NOT_RUN":
            failures.append(_fail(ProviderOff,
                                  f"live_status {compat.get('live_status')!r} claims a live run "
                                  "while the provider is off", path))
        if compat.get("mode") != "FIXTURE_MOCK":
            failures.append(_fail(ProviderOff,
                                  f"compatibility mode {compat.get('mode')!r} claims more than "
                                  "fixture/mock", path))
    for recs, fields, name in ((record["capability_loss"], LOSS_FIELDS, "CapabilityLoss"),
                               (record["nack"], NACK_FIELDS, "NACK")):
        if not isinstance(recs, list) or not recs:
            failures.append(_fail(EmptyPayload, f"no {name} record carried", path))
            continue
        for item in recs:
            for key in fields:
                if key not in item or item[key] in (None, ""):
                    failures.append(_fail(MissingField, f"{name} record missing {key}", path))
                    break
    host_spec = ADAPTER_MAPPING["hosts"][surface]
    declared_losses = {r["loss_id"] for r in host_spec["capability_loss"]}
    carried_losses = {r.get("loss_id") for r in record["capability_loss"] or []}
    if not declared_losses <= carried_losses:
        failures.append(_fail(MissingField,
                              f"capability-loss record missing {sorted(declared_losses - carried_losses)}",
                              path))
    provider = record["provider"]
    expected_provider = host_spec["provider"]
    if not isinstance(provider, dict):
        failures.append(_fail(MissingField, "provider record missing", path))
    else:
        if provider.get("live_integration") is not False:
            failures.append(_fail(ProviderOff,
                                  "provider claimed live integration while it is off "
                                  f"({expected_provider['provider_id']} {expected_provider['admission_state']})",
                                  path))
        if provider.get("admission_state") != expected_provider["admission_state"]:
            failures.append(_fail(ProviderOff,
                                  f"provider admission state {provider.get('admission_state')!r} "
                                  f"diverges from authoritative {expected_provider['admission_state']!r}",
                                  path))
    allowed = set(host_spec["allowed_permissions"])
    for perm in record["permissions"]:
        if perm not in allowed:
            failures.append(_fail(PermissionWidening,
                                  f"permission {perm!r} is outside the host contract {sorted(allowed)}",
                                  path))
    for scope_entry in record["scope"]:
        if scope_entry not in ALLOWED_SCOPE:
            failures.append(_fail(ScopeWidening,
                                  f"scope {scope_entry!r} widens beyond {list(ALLOWED_SCOPE)}", path))


def _check_required_mappings(record: dict, surface: str, path: str, failures: list) -> None:
    host_spec = ADAPTER_MAPPING["hosts"][surface]
    required = set(host_spec["required_mappings"])
    kind = record["entry_kind"]
    payload = record.get("payload") or {}
    if kind == "skill_projection":
        carried = set(payload.get("contract_refs", []))
    elif kind == "receiver_map":
        carried = {r.get("source_object_id") for r in payload.get("receivers", [])}
    else:
        carried = {m.get("source_object_id") for m in payload.get("mappings", [])}
    missing = sorted(required - carried)
    if missing:
        failures.append(_fail(MissingRequiredMapping,
                              f"missing required mapping for {missing}", path))


def _load_skill_projection(record: dict, path: str, failures: list) -> dict:
    skill = record.get("payload") or {}
    for key in ("skill_id", "trigger", "non_trigger", "contract_refs",
                "input_object_id", "output_object_id"):
        if key not in skill or skill[key] in (None, "", []):
            failures.append(_fail(MissingField, f"skill payload missing {key}", path))
    if skill.get("skill_id") != ADAPTER_MAPPING["hosts"]["host:generic-skills"]["skill_id"]:
        failures.append(_fail(MissingField, "skill_id does not match the adapter mapping", path))
    return {"loader": "skill_projection_v1", "skill_id": skill.get("skill_id"),
            "contract_refs": skill.get("contract_refs", [])}


def _load_receiver_map(record: dict, path: str, failures: list) -> dict:
    payload = record.get("payload") or {}
    receivers = payload.get("receivers")
    if not isinstance(receivers, list) or not receivers:
        failures.append(_fail(EmptyPayload, "receiver map carries no receivers", path))
        return {"loader": "receiver_map_v1", "receivers": 0}
    seen = set()
    typed = 0
    for receiver in receivers:
        for key in ("receiver_id", "source_object_id", "entry", "ack_state", "fields"):
            if key not in receiver:
                failures.append(_fail(MissingField, f"receiver missing {key}", path))
                break
        else:
            if receiver["receiver_id"] in seen:
                failures.append(_fail(MissingField,
                                      f"duplicate receiver id {receiver['receiver_id']}", path))
            seen.add(receiver["receiver_id"])
            if not receiver["fields"]:
                failures.append(_fail(EmptyPayload,
                                      f"receiver {receiver['receiver_id']} has no typed fields", path))
            for field_row in receiver["fields"]:
                for key in ("name", "type", "required"):
                    if key not in field_row:
                        failures.append(_fail(MissingField,
                                              f"receiver field missing {key}", path))
                        break
                else:
                    if field_row["type"] not in TYPE_VOCAB:
                        failures.append(_fail(MissingField,
                                              f"receiver field type {field_row['type']!r} "
                                              "is not in the type vocabulary", path))
                    typed += 1
    return {"loader": "receiver_map_v1", "receivers": len(receivers), "typed_fields": typed}


def _load_object_crosswalk(record: dict, path: str, failures: list) -> dict:
    payload = record.get("payload") or {}
    mappings = payload.get("mappings")
    if not isinstance(mappings, list) or not mappings:
        failures.append(_fail(EmptyPayload, "object crosswalk carries no mappings", path))
        return {"loader": "object_crosswalk_v1", "mappings": 0}
    targets_required = set(_required_targets(load_canonical_objects_cache,
                                             ADAPTER_MAPPING["hosts"]["host:genie-adapter"]))
    carried_targets = set()
    for mapping in mappings:
        for key in ("source_object_id", "source_schema", "source_version", "target",
                    "target_ref", "direction"):
            if key not in mapping or mapping[key] in (None, ""):
                failures.append(_fail(MissingField, f"mapping missing {key}", path))
                break
        else:
            if mapping["direction"] != "REFERENCE_ONLY":
                failures.append(_fail(ScopeWidening,
                                      f"mapping direction {mapping['direction']!r} is not "
                                      "reference-only (no truth writeback)", path))
            if mapping["target"] in targets_required:
                carried_targets.add(mapping["target"])
    missing = sorted(targets_required - carried_targets)
    if missing:
        failures.append(_fail(MissingRequiredMapping,
                              f"missing required target mapping {missing}", path))
    return {"loader": "object_crosswalk_v1", "mappings": len(mappings),
            "targets": sorted(carried_targets)}


_LOADERS = {
    "skill_projection": _load_skill_projection,
    "receiver_map": _load_receiver_map,
    "object_crosswalk": _load_object_crosswalk,
}


# module-level cache set by check functions (pure reads of the given root)
load_canonical_objects_cache: dict[str, Any] = {}


def _check_host_dir(out: Path, surface: str, expected_art: dict, failures: list) -> dict:
    host_spec = ADAPTER_MAPPING["hosts"][surface]
    d = out / host_spec["dir"]
    path = f"{host_spec['dir']}/{host_spec['entry_file']}"
    row = {"host": surface, "path": path, "loader": host_spec["loader"],
           "effective_load": False, "resolved": None}
    if not d.is_dir():
        failures.append(_fail(MissingRequiredHost, f"host projection dir {host_spec['dir']} absent",
                              host_spec["dir"]))
        return row
    entry = d / host_spec["entry_file"]
    if not entry.is_file():
        failures.append(_fail(HostEntryMissing, f"host entry {host_spec['entry_file']} absent", path))
        return row
    text = entry.read_text(encoding="utf-8")
    if not text.strip():
        failures.append(_fail(EmptyPayload, "host entry is empty", path))
        return row

    record = None
    if host_spec["entry_kind"] == "skill_projection":
        fm = _FRONTMATTER_RE.match(text)
        block = _RECORD_RE.search(text)
        if not fm or not block:
            failures.append(_fail(MarkerOnlyStub,
                                  "skill projection has no loadable frontmatter/record "
                                  "(marker-only stub cannot be effective-loaded)", path))
            return row
        front = {}
        for line in fm.group(1).splitlines():
            if ": " in line:
                k, v = line.split(": ", 1)
                front[k.strip()] = v.strip()
        if "name" not in front or "description" not in front:
            failures.append(_fail(MissingField, "skill frontmatter missing name/description", path))
        try:
            record = json.loads(block.group(1))
        except json.JSONDecodeError as exc:
            failures.append(_fail(InvalidEntry, f"host record block is not JSON: {exc}", path))
            return row
    else:
        try:
            record = json.loads(text)
        except json.JSONDecodeError as exc:
            failures.append(_fail(InvalidEntry, f"host entry is not JSON: {exc}", path))
            return row

    if not isinstance(record, dict) or not record.get("source_refs") or not record.get("field_contract"):
        failures.append(_fail(MarkerOnlyStub,
                              "host entry is a marker-only stub: no field contract / source "
                              "references, so effective load cannot be satisfied", path))
        return row

    _check_record_common(record, expected_art["payload"], path, failures)
    _check_required_mappings(record, surface, path, failures)
    resolved = _LOADERS[host_spec["entry_kind"]](record, path, failures)
    if record != expected_art["payload"]:
        failures.append(_fail(NotDerived,
                              "host entry is not the derivation of the canonical sources "
                              "(free-text or tampered projection)", path))
    row["source_ref_hashes"] = {r.get("object_id", f"ref-{i}"): r.get("source_hash", "")
                                for i, r in enumerate(record.get("source_refs") or [])
                                if isinstance(r, dict)}
    row["resolved"] = resolved
    row["effective_load"] = not any(f["path"] == path for f in failures)
    return row


def check_host_surfaces(root: Path, out: Path) -> dict[str, Any]:
    """G-S3-HOST semantic gate: three hosts, real effective loads, typed refusals."""
    global load_canonical_objects_cache
    out = Path(out)
    load_canonical_objects_cache = load_canonical_objects(root)
    ir = compile_projection_ir(root)
    failures: list[dict] = []
    rows: list[dict] = []

    expected_dirs = {spec["dir"] for spec in ADAPTER_MAPPING["hosts"].values()}
    present_dirs = {p.name for p in out.iterdir() if p.is_dir() and p.name.startswith("host_")} \
        if out.is_dir() else set()
    for extra in sorted(present_dirs - expected_dirs):
        failures.append(_fail(UnsupportedHost, f"unsupported host projection {extra!r}", extra))
    for missing in sorted(expected_dirs - present_dirs):
        failures.append(_fail(MissingRequiredHost, f"required host projection {missing!r} absent",
                              missing))

    artifacts_by_path = {a["path"]: a for a in ir["artifacts"]}
    for surface, host_spec in ADAPTER_MAPPING["hosts"].items():
        expected_art = artifacts_by_path[f"{host_spec['dir']}/{host_spec['entry_file']}"]
        rows.append(_check_host_dir(out, surface, expected_art, failures))

    # semantic parity: every host binds to the same live canonical truth
    parity = "PASS"
    seen: dict[str, str] = {}
    for row in rows:
        for object_id, digest in (row.get("source_ref_hashes") or {}).items():
            if seen.setdefault(object_id, digest) != digest:
                parity = "FAIL"
                failures.append(_fail(ParityMismatch,
                                      f"source object {object_id} diverges between host projections",
                                      row["path"]))

    verdict = "PASS" if not failures else "FAIL"
    return {
        "schema": "PIPD-HOST-PROJECTIONS-CHECK/1",
        "surface": "host",
        "verdict": verdict,
        "host_count": f"{sum(1 for r in rows if r['effective_load'])}/{len(ADAPTER_MAPPING['hosts'])}",
        "required_hosts": sorted(ADAPTER_MAPPING["hosts"]),
        "rows": rows,
        "semantic_parity": parity if not failures else "FAIL",
        "capability_loss": {surface: [r["loss_id"] for r in spec["capability_loss"]]
                            for surface, spec in ADAPTER_MAPPING["hosts"].items()},
        "compatibility": {surface: _compatibility(load_canonical_objects_cache, spec)
                          for surface, spec in ADAPTER_MAPPING["hosts"].items()},
        "claims": dict(CLAIMS),
        "projection_parity_sha256": ir["projection_parity_sha256"],
        "failures": failures,
        "first_failing_invariant": (f"{failures[0]['code']}: {failures[0]['reason']}"
                                    if failures else ""),
    }


def check_web_surface(root: Path, out: Path) -> dict[str, Any]:
    """G-S3-WEB semantic gate: exactly the five PIPD documents, source-derived,
    with capability-loss and NACK records. OPTIONAL_SITE_UI is excluded."""
    out = Path(out)
    ir = compile_projection_ir(root)
    validate_projection_ir(ir)
    failures: list[dict] = []
    rows: list[dict] = []

    expected_top = set(WEB_DOC_FILES) | {IR_FILE, UI_DIR} \
        | {spec["dir"] for spec in ADAPTER_MAPPING["hosts"].values()}
    present_top = {p.name for p in out.iterdir()} if out.is_dir() else set()
    if present_top != expected_top:
        failures.append(_fail(WrongWebSet,
                              f"web surface set mismatch: expected {sorted(expected_top)}, "
                              f"present {sorted(present_top)} — the site UI five files can never "
                              "be the Web pack", "dist/web"))

    artifacts_by_path = {a["path"]: a for a in ir["artifacts"]}
    for art in ir["artifacts"]:
        if art["kind"] != WEB_DOC_KIND:
            continue
        path = art["path"]
        fpath = out / path
        row = {"doc_id": art["payload"]["doc_id"], "path": path,
               "source_hash": art["source_hash"], "source_objects": len(art["source_objects"]),
               "capability_loss": len(art["capability_loss"]), "nack": len(art["nack"]),
               "denominator": art["denominator"], "fresh": False, "derived": False}
        rows.append(row)
        if not fpath.is_file():
            failures.append(_fail(WrongWebSet, f"web document {path} absent", path))
            continue
        text = fpath.read_text(encoding="utf-8")
        if not text.strip():
            failures.append(_fail(EmptyPayload, f"web document {path} is empty", path))
            continue
        match = _META_RE.search(text)
        if not match:
            failures.append(_fail(MissingField, f"web document {path} has no PIPD-DOC-META block",
                                  path))
            continue
        try:
            meta = json.loads(match.group(1))
        except json.JSONDecodeError as exc:
            failures.append(_fail(MissingField, f"meta block is not JSON: {exc}", path))
            continue
        for key in ("schema", "schema_version", "doc_id", "kind", "denominator",
                    "source_objects", "source_hash", "capability_loss", "nack", "scope"):
            if key not in meta:
                failures.append(_fail(MissingField, f"meta block missing {key}", path))
                break
        else:
            if meta["kind"] != WEB_DOC_KIND:
                failures.append(_fail(DenominatorLeak,
                                      f"document kind {meta['kind']!r} is not a web document", path))
            if meta["denominator"] is not True:
                failures.append(_fail(DenominatorLeak,
                                      "web document was removed from the denominator", path))
            for scope_entry in meta["scope"]:
                if scope_entry not in ALLOWED_SCOPE:
                    failures.append(_fail(ScopeWidening,
                                          f"meta scope {scope_entry!r} widens authority", path))
            for recs, fields, name in ((meta["capability_loss"], LOSS_FIELDS, "CapabilityLoss"),
                                       (meta["nack"], NACK_FIELDS, "NACK")):
                if not isinstance(recs, list) or not recs:
                    failures.append(_fail(EmptyPayload,
                                          f"document {path} carries no {name} record", path))
                    continue
                for item in recs:
                    for key in fields:
                        if key not in item or item[key] in (None, ""):
                            failures.append(_fail(MissingField,
                                                  f"{name} record missing {key}", path))
                            break
            fresh = True
            for ref in meta["source_objects"]:
                for key in SOURCE_REF_FIELDS:
                    if key not in ref or not ref[key]:
                        failures.append(_fail(MissingField, f"source ref missing {key}", path))
                        fresh = False
                        break
                else:
                    live = ir["source_index"]
                    live_hashes = {r["object_id"]: r["source_hash"] for r in live}
                    if ref["object_id"] not in live_hashes:
                        failures.append(_fail(UnknownSourceObject,
                                              f"unknown source object {ref['object_id']!r}", path))
                        fresh = False
                    elif ref["source_hash"] != live_hashes[ref["object_id"]]:
                        failures.append(_fail(StaleSource,
                                              f"stale source hash for {ref['object_id']}; "
                                              "regenerate the projection", path))
                        fresh = False
            row["fresh"] = fresh
            if meta["source_hash"] != art["source_hash"]:
                failures.append(_fail(StaleSource,
                                      f"document source hash {meta['source_hash']} != live "
                                      f"{art['source_hash']}", path))
        if text != render_web_doc(art):
            failures.append(_fail(NotDerived,
                                  f"web document {path} content is not derived from the canonical "
                                  "objects/profiles (free text or tampered)", path))
        else:
            row["derived"] = True

    # PROJECTION_IR.json traceability + the three mandated IR negatives on disk
    ir_path = out / IR_FILE
    if ir_path.is_file():
        try:
            disk_ir = json.loads(ir_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            failures.append(_fail(MissingField, f"PROJECTION_IR.json is not JSON: {exc}", IR_FILE))
            disk_ir = None
        if disk_ir is not None:
            try:
                validate_projection_ir(disk_ir)
                if disk_ir.get("projection_parity_sha256") != ir["projection_parity_sha256"]:
                    failures.append(_fail(ParityMismatch,
                                          "PROJECTION_IR.json parity hash diverges from the "
                                          "canonical sources", IR_FILE))
            except ProjectionError as exc:
                failures.append(exc.failure(IR_FILE))
    else:
        failures.append(_fail(MissingField, "PROJECTION_IR.json absent", IR_FILE))

    # OPTIONAL_SITE_UI: present, exactly the five files, never in the denominator
    ui_dir = out / UI_DIR
    if ui_dir.is_dir():
        ui_present = sorted(p.name for p in ui_dir.iterdir() if p.is_file())
        if ui_present != sorted(UI_FILES):
            failures.append(_fail(WrongWebSet,
                                  f"OPTIONAL_SITE_UI file set {ui_present} != {sorted(UI_FILES)}",
                                  UI_DIR))
    for art in ir["artifacts"]:
        if art["kind"] == UI_KIND and art["denominator"]:
            failures.append(_fail(DenominatorLeak,
                                  "OPTIONAL_SITE_UI leaked into the Web denominator", UI_DIR))

    denominator_docs = [r for r in rows if r["denominator"]]
    verdict = "PASS" if not failures else "FAIL"
    return {
        "schema": "PIPD-WEB-PACK-CHECK/1",
        "surface": "web",
        "verdict": verdict,
        "expected": sorted(WEB_DOC_FILES),
        "denominator": {"expected": 5, "present": len(denominator_docs),
                        "ratio": f"{len(denominator_docs)}/5",
                        "optional_site_ui_excluded": len(UI_FILES),
                        "note": "exact-set equality over the five PIPD documents; OPTIONAL_SITE_UI "
                                "is excluded from the denominator and can never pass"},
        "rows": rows,
        "capability_loss": [r for art in ir["artifacts"] if art["kind"] == WEB_DOC_KIND
                            for r in art["capability_loss"]][:len(WEB_CAPABILITY_LOSS)],
        "nack": [r for art in ir["artifacts"] if art["kind"] == WEB_DOC_KIND
                 for r in art["nack"]][:len(WEB_NACK)],
        "claims": dict(CLAIMS),
        "projection_parity_sha256": ir["projection_parity_sha256"],
        "failures": failures,
        "first_failing_invariant": (f"{failures[0]['code']}: {failures[0]['reason']}"
                                    if failures else ""),
    }
